BookAMechanicc/Controllers/MechanicController.cs
using BookAMechanicc.Data;
using BookAMechanicc.Models;
using Microsoft.AspNetCore.Mvc;

namespace BookAMechanicc.Controllers
{
    public class MechanicController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public MechanicController(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            db = context;
            _httpContextAccessor = httpContextAccessor;
        }
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ManageMechanic()
        {
            var httpContext = _httpContextAccessor.HttpContext;
            try
            {
                string isMech = httpContext.Session.GetString("isMech");
                if (isMech != "True")
                {
                    return RedirectToAction("Login", "Login");
                }
            }
            catch (Exception)
            {
                return RedirectToAction("Login", "Login");

            }
            try
            {
                bool isAdded = (bool)TempData["isAdded"];
                string feedback = (string)TempData["feedback"];
                ViewBag.isAdded = isAdded;
                ViewBag.feedback = feedback;
            }
            catch (Exception)
            {
            }
            int id = (int)httpContext.Session.GetInt32("id");
            tbl_mechanic user = db.tbl_mechanic.Where(x => x.id == id).FirstOrDefault();
            return View(user);
        }
        public ActionResult CurrentOrder()
        {
            var httpContext = _httpContextAccessor.HttpContext;
            try
            {
                string isMech = httpContext.Session.GetString("isMech");
                if (isMech != "True")
                {
                    return RedirectToAction("Login", "Login");
                }
            }
            catch (Exception)
            {
                return RedirectToAction("Login", "Login");

            }
            try
            {
                bool isApproved = (bool)TempData["isApproved"];
                string feeback = TempData["feedback"] as string;
            }
            catch (Exception)
            {


            }
            int id = (int)httpContext.Session.GetInt32("id");
            tbl_mechanic user = db.tbl_mechanic.Where(x => x.id == id).FirstOrDefault();
            List<tbl_order> currOrders = db.tbl_order.Where(x => x.mechanic_id == user.id).ToList();
            return View(currOrders.Where(x => x.status == "pending" || x.status == "ongoing" || x.status == "review").ToList());
        }
        public ActionResult OrderHistory()
        {
            var httpContext = _httpContextAccessor.HttpContext;
            try
            {
                string isMech = httpContext.Session.GetString("isMech");
                if (isMech != "True")
                {
                    return RedirectToAction("Login", "Login");
                }
            }
            catch (Exception)
            {
                return RedirectToAction("Login", "Login");

            }

            int id = (int)httpContext.Session.GetInt32("id");
            tbl_mechanic user = db.tbl_mechanic.Where(x => x.id == id).FirstOrDefault();
            List<tbl_order> orders = db.tbl_order.Where(x => x.mechanic_id == user.id).ToList();
            return View(orders.Where(x => x.status == "completed" || x.status == "cancelled"));
        }



        //methods that perform some functionality
        [HttpPost]
        public ActionResult EditMechanic(tbl_mechanic emp)
        {
            var httpContext = _httpContextAccessor.HttpContext;
            tbl_mechanic existingEmployee = db.tbl_mechanic.Find(emp.id);
            bool isAdded = false;
            try
            {
                existingEmployee.firstname = emp.firstname;
                existingEmployee.lastname = emp.lastname;
                existingEmployee.username = emp.username;
                existingEmployee.password = emp.password;
                existingEmployee.garageName = emp.garageName;
                existingEmployee.contact = emp.contact;
                existingEmployee.address = emp.address;
                existingEmployee.isBooked = emp.isBooked;
                existingEmployee.isOnline = emp.isOnline;
                existingEmployee.avg_rating = emp.avg_rating;
                db.SaveChanges();
                TempData["feedback"] = "Record Updated Successfully";
                isAdded = true;
            }
            catch (Exception ex)
            {
                TempData["feedback"] = "Unable to Update Record";
            }
            TempData["isAdded"] = isAdded;
            httpContext.Session.SetInt32("id", existingEmployee.id);
            return RedirectToAction("ManageMechanic");
        }

        public ActionResult Approve(int id)
        {
            var httpContext = _httpContextAccessor.HttpContext;
            bool isApproved = false;
            tbl_order order = db.tbl_order.Where(x => x.id == id).FirstOrDefault();
            int custid = order.customer_id;
            int mechid = order.mechanic_id;
            tbl_customer customer = db.tbl_customer.Where(x => x.id == custid).FirstOrDefault();
            tbl_mechanic mechanic = db.tbl_mechanic.Where(x => x.id == mechid).FirstOrDefault();
            if (customer.isBooked)
            {
                TempData["feedback"] = "Customer is already Booked!";
                TempData["isApproved"] = isApproved;
                return RedirectToAction("CurrentOrder");
            }
            try
            {
                order.status = "ongoing";
                customer.isBooked = true;
                mechanic.isBooked = true;
                db.SaveChanges();
                TempData["feedback"] = "Order Approved successfully";
                isApproved = true;
            }
            catch (Exception ex)
            {
                TempData["feedback"] = "Couldn't approve order! Try Again!";
            }
            TempData["isApproved"] = isApproved;
            return RedirectToAction("CurrentOrder");
        }

        public ActionResult Decline(int id)
        {
            var httpContext = _httpContextAccessor.HttpContext;
            bool isDeclined = false;
            tbl_order order = db.tbl_order.Where(x => x.id == id).FirstOrDefault();
            try
            {
                order.status = "declined";
                db.SaveChanges();
                TempData["feedback"] = "Order Declined";
                isDeclined = true;
            }
            catch (Exception ex)
            {
                TempData["feedback"] = "Couldn't decline order! Try Again!";
            }

            TempData["isApproved"] = isDeclined;
            return RedirectToAction("CurrentOrder");
        }

        public ActionResult CancelOrder(int id)
        {
            var httpContext = _httpContextAccessor.HttpContext;
            bool isDeclined = false;
            tbl_order order = db.tbl_order.Where(x => x.id == id).FirstOrDefault();
            try
            {
                tbl_cancel cancel = new tbl_cancel
                {
                    order_id = order.id,
                    cancelled_by = "mechanic",
                    reason = "No Reason"
                };
                order.status = "cancelled";
                order.tbl_customer.isBooked = false;
                order.tbl_mechanic.isBooked = false;
                order.tbl_cancel.Add(cancel);
                db.SaveChanges();
                isDeclined = true;
            }
            catch (Exception ex)
            {

            }
            return RedirectToAction("CurrentOrder");
        }

        public ActionResult ReviewOrder(int id)
        {

            return View(db.tbl_order.Where(x => x.id == id).FirstOrDefault());
        }

        public ActionResult ViewDetails(int id)
        {
            var httpContext = _httpContextAccessor.HttpContext;
            tbl_order order = db.tbl_order.Where(x => x.id == id).FirstOrDefault();
            if (order.status.Equals("completed"))
            {
                ViewBag.completed = db.tbl_completed.Where(x => x.order_id == id).FirstOrDefault();
            }
            else
            {
                ViewBag.cancelled = db.tbl_cancel.Where(x => x.order_id == id).FirstOrDefault();
            }
            return View(db.tbl_order.Where(x => x.id == id).FirstOrDefault());
        }

        [HttpPost]
        public ActionResult ReviewOrder(int id, string review, string rating)
        {
            var httpContext = _httpContextAccessor.HttpContext;
            //int orderid = (int)Session["orderId"];
            tbl_order order = db.tbl_order.Where(x => x.id == id).FirstOrDefault();
            tbl_completed complete = db.tbl_completed.Where(x => x.order_id == id).FirstOrDefault();
            tbl_customer customer = db.tbl_customer.Where(x => x.id == order.customer_id).FirstOrDefault();
            tbl_mechanic mechanic = db.tbl_mechanic.Where(x => x.id == order.mechanic_id).FirstOrDefault();
            try
            {
                complete.mechanic_review = review;
                complete.mechanic_rating = Convert.ToInt32(rating);
                complete.complete_date = DateTime.Now;
                order.status = "completed";
                customer.isBooked = false;
                mechanic.isBooked = false;
                order.tbl_completed.Add(complete);
                db.SaveChanges();
            }
            catch (Exception ex)
            {

            }
            return RedirectToAction("OrderHistory");
        }
    }
}

BookAMechanicc/Views/Mechanic/ManageMechanic.cshtml
@model BookAMechanicc.Models.tbl_mechanic
@{
    ViewBag.Title = "ManageMechanic";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (ViewBag.isAdded != null)
{
    if ((bool)ViewBag.isAdded)
    {
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>Success!</strong> @ViewBag.feedback.
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
    else
    {
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>Ops!</strong> @ViewBag.feedback.
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
}

<div class="nk-block-head">
    <div class="nk-block-head-content">
        <div class="nk-block-head-sub"><span>Account Setting</span></div>
        <h2 class="nk-block-title fw-normal">My Profile</h2>
        <div class="nk-block-des">
            <p>You have full control to manage your own account setting. <span class="text-primary"><em class="icon ni ni-info"></em></span></p>
        </div>
    </div>
</div><!-- .nk-block-head -->
<!-- nav-tabs -->
<div class="nk-block">
    <div class="nk-block-head">
        <div class="nk-block-head-content">
            <h5 class="nk-block-title">Personal Information</h5>
            <div class="nk-block-des">
                <p>Basic info, like your name and address.</p>
            </div>
        </div>
    </div><!-- .nk-block-head -->
    <div class="card card-bordered">
        <div class="nk-data data-list">
            <div class="data-item" data-toggle="modal" data-target="#profile-edit">
                <div class="data-col">
                    <span class="data-label">Full Name</span>
                    <span class="data-value">@Model.firstname @Model.lastname</span>
                </div>
                <div class="data-col data-col-end"><span class="data-more"><em class="icon ni ni-forward-ios"></em></span></div>
            </div><!-- .data-item -->
            <div class="data-item">
                <div class="data-col">
                    <span class="data-label">Username</span>
                    <span class="data-value">@Model.username</span>
                </div>
                <div class="data-col data-col-end"><span class="data-more disable"><em class="icon ni ni-lock-alt"></em></span></div>
            </div><!-- .data-item -->
            <div class="data-item" data-toggle="modal" data-target="#profile-edit">
                <div class="data-col">
                    <span class="data-label">Phone Number</span>
                    <span class="data-value text-soft">@Model.contact</span>
                </div>
                <div class="data-col data-col-end"><span class="data-more"><em class="icon ni ni-forward-ios"></em></span></div>
            </div><!-- .data-item -->
            <div class="data-item" data-toggle="modal" data-target="#profile-edit">
                <div class="data-col">
                    <span class="data-label">Address</span>
                    <span class="data-value">@Model.address</span>
                </div>
                <div class="data-col data-col-end"><span class="data-more"><em class="icon ni ni-forward-ios"></em></span></div>
            </div>
            <div class="data-item" data-toggle="modal" data-target="#profile-edit">
                <div class="data-col">
                    <span class="data-label">Garage Name</span>
                    <span class="data-value">@Model.garageName</span>
                </div>
                <div class="data-col data-col-end"><span class="data-more"><em class="icon ni ni-forward-ios"></em></span></div>
            </div>
            <div class="data-item" data-toggle="modal" data-target="#profile-edit">
                <div class="data-col">
                    <span class="data-label">Rating</span>
                    <span class="data-value">@Model.avg_rating</span>
                </div>
                <div class="data-col data-col-end"><span class="data-more"><em class="icon ni ni-forward-ios"></em></span></div>
            </div><!-- .data-item -->
        </div><!-- .nk-data -->
    </div><!-- .card -->
    <!-- Another Section -->
    <!-- .nk-block-head -->
    <!-- .card -->
</div><!-- .nk-block -->
<!-- @@ Profile Edit Modal  -->
<div class="modal fade" tabindex="-1" role="dialog" id="profile-edit">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <a href="#" class="close" data-dismiss="modal"><em class="icon ni ni-cross-sm"></em></a>
            <div class="modal-body modal-body-lg">
                <h5 class="title">Update Profile</h5>
                <ul class="nk-nav nav nav-tabs">
                    <li class="nav-item">
                        <a class="nav-link active" data-toggle="tab" href="#personal">Personal</a>
                    </li>
                </ul><!-- .nav-tabs -->
                <form action="Mechanic/EditMechanic" method="post">
                    @Html.HiddenFor(x => x.id)
                    @Html.HiddenFor(x => x.isBooked)
                    @Html.HiddenFor(x => x.avg_rating)
                    @Html.HiddenFor(x => x.username)
                    <div class="tab-content">
                        <div class="tab-pane active" id="personal">
                            <div class="row gy-4">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="form-label" for="firstname">First Name</label>
                                        @*<input type="text" class="form-control form-control-lg" id="firstname"  name="firstname" placeholder="Enter First name">*@
                                        @Html.TextBoxFor(x => x.firstname, new { @class = "form-control form-control-lg", @placeholder = "Enter First name" })
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="form-label" for="lastname">Last Name</label>
                                        @*<input type="text" class="form-control form-control-lg" id="lastname" name="lastname" placeholder="Enter Last name">*@
                                        @Html.TextBoxFor(x => x.lastname, new { @class = "form-control form-control-lg", @placeholder = "Enter Last name" })
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="form-label" for="garageName">Garage Name</label>
                                        @*<input type="text" class="form-control form-control-lg" id="lastname" name="lastname" placeholder="Enter Last name">*@
                                        @Html.TextBoxFor(x => x.garageName, new { @class = "form-control form-control-lg", @placeholder = "Enter Garage name" })
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="form-label" for="password">Password</label>
                                        @*<input type="text" class="form-control form-control-lg" name="password" id="password" placeholder="Enter new Password">*@
                                        @Html.TextBoxFor(x => x.password, new { @class = "form-control form-control-lg", @placeholder = "Enter new password" })
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="form-label" for="contact">Phone Number</label>
                                        @*<input type="text" class="form-control form-control-lg" id="contact" name="contact" placeholder="+92-3xxxxxxx">*@
                                        @Html.TextBoxFor(x => x.contact, new { @class = "form-control form-control-lg", @placeholder = "+92-321xxxxxxx" })
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="form-label" for="address">Address</label>
                                        @*<input type="text" class="form-control form-control-lg" id="address" name="address" placeholder="Enter Address">*@
                                        @Html.TextBoxFor(x => x.address, new { @class = "form-control form-control-lg", @placeholder = "Enter Address" })
                                    </div>
                                </div>
                                <div class="col-12">
                                    <ul class="align-center flex-wrap flex-sm-nowrap gx-4 gy-2">
                                        <li>
                                            <button type="submit" class="btn btn-lg btn-primary">Update Profile</button>
                                        </li>
                                        <li>
                                            <a href="#" data-dismiss="modal" class="btn btn-lg btn-danger ">Cancel</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div><!-- .tab-pane --><!-- .tab-pane -->
                    </div><!-- .tab-content -->
                </form>
            </div><!-- .modal-body -->
        </div><!-- .modal-content -->
    </div><!-- .modal-dialog -->
</div><!-- .modal -->

BookAMechanicc/Views/Mechanic/OrderHistory.cshtml
@model IEnumerable<BookAMechanicc.Models.tbl_order>
@{
    ViewBag.Title = "OrderHistory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="nk-content-wrap">
    <div class="nk-block-head nk-block-head-lg">
        <div class="nk-block-between-md g-4">
            <div class="nk-block-head-content">
                <h2 class="nk-block-title fw-normal">All Orders</h2>
                <div class="nk-block-des">
                    <p>Here is your current order of account that needs reviewing.</p>
                </div>
            </div>
        </div>
    </div><!-- .nk-block-head -->
    <div class="nk-block">
        <div class="card card-bordered">
            <table class="table table-tranx table-billing">
                <thead>
                    <tr class="tb-tnx-head">
                        <th class="tb-tnx-id"><span class="">#</span></th>
                        <th class="tb-tnx-info">
                            <span class="tb-tnx-desc d-none d-sm-inline-block">
                                <span>Customer Id</span>
                            </span>
                            <span class="tb-tnx-date d-md-inline-block d-none">
                                <span class="d-md-none">Date</span>
                                <span class="d-none d-md-block">
                                    <span>Issue Date</span>
                                    <span>Issue Time</span>
                                </span>
                            </span>
                        </th>
                        <th class="tb-tnx-id"><span class="">Service</span></th>
                        <th class="tb-tnx-amount">
                            <span class="tb-tnx-total">Total</span>
                            <span class="tb-tnx-status d-none d-md-inline-block">Status</span>
                        </th>
                    </tr><!-- .tb-tnx-head -->
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        var date = item.order_date.ToLongDateString();
                        var time = item.order_date.ToShortTimeString();

                        <tr class="tb-tnx-item">
                            <td class="tb-tnx-id">
                                <span>@Html.DisplayFor(modelItem => item.id)</span>
                            </td>
                            <td class="tb-tnx-info">
                                <div class="tb-tnx-desc">
                                    <span class="title">@Html.DisplayFor(modelItem => item.customer_id) </span>
                                </div>
                                <div class="tb-tnx-date">
                                    <span class="date">@Html.DisplayFor(modelItem => date)</span>
                                    <span class="date">@Html.DisplayFor(modelItem => time)</span>
                                </div>
                            </td>
                            <td class="tb-tnx-id">
                                <span>@Html.DisplayFor(modelItem => item.service)</span>
                            </td>
                            <td class="tb-tnx-amount">
                                <div class="tb-tnx-total">
                                    <span class="amount">@Html.DisplayFor(modelItem => item.order_price)</span>
                                </div>
                                <div class="tb-tnx-status">
                                    <span class="badge badge-dot badge-success">@Html.DisplayFor(modelItem => item.status)</span>
                                </div>
                            </td>
                            <td>
                                <div class="nk-tb-col nk-tb-col-tools">
                                    <ul class="nk-tb-actions gx-2">
                                        <li class="nk-tb-action">
                                            <a href="@Url.Action("ViewDetails", "Mechanic", new { id = item.id })" class="btn btn-sm btn-icon btn-trigger" data-toggle="tooltip" data-placement="top" title="View Details">
                                                <em class="icon ni ni-eye-alt-fill "></em>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </td>
                        </tr>

                        <!-- .tb-tnx-item -->
                    }

                </tbody>
            </table>
        </div>
    </div><!-- .nk-block -->
</div>